# Sampling data

When discussing sampling, it is impossible to avoid discussing random number generation.

The fact that we are claiming to sample randomly is something that has an impact on the actual implementation of the whole method we use for sampling. In fact, on numerous occasions, we will run into code that has certain parameters we need to set that account for the seed we are using.

Random number(s) can be generated in many ways:
    1. "random()" for a single float number in [0,1),
    2. "random.randint(lowerBound, upperBound)" for an integer within an interval,
    3. "random.randrange(lowerBound, upperBound, step)" for further constraining on the range. (e.g. randrange(0,11,2) randomly generates even number within [0,11).)
    4. "random.uniform(a,b)" for a random float number within interval [a,b). Here a doesn't have to be smaller than b. Method 1-3 will cause TypeError or ValueError if a<b.
    .etc

Here we introduce the random generator from NumPy as follows, which generates an array of length 3 with numbers between 0 and 5 (not including 5):

In [8]:
import numpy as np

# Generates a random sample from a given 1-D array.
np.random.choice(5,3)
# #This is equivalent to np.random.randint(0,5,3)

array([0, 3, 2])

This generation is random. Another run will give you a different array.

In [9]:
np.random.choice(5,3)

array([3, 1, 1])

### Generating random samples with seed.

In [10]:
# to initialise the random number generator
np.random.seed(3)

np.random.choice(5,3)

array([2, 0, 1])

In [11]:
np.random.choice(5,3)

array([3, 0, 0])

If you restart and rerun this notebook, you will notice that the result of the first two times generating an array will give you different results each time.

However, as soon as you run the line that sets the seed, all the results **afterwards** will be the **same** and appear in the **same order**. This is because you use a certain stream of previously generated random numbers that are kept in an array.

This is quite counterintuitive. We want to be random, but we want predictable random. The latter is especially useful if we want to test a piece of code. If we want to find our mistakes or just test the rationale, we don't want to keep running it in order to see whether that one particular instance that was causing an error is reoccurring.

(The random samples generated by seed is traceable.)

In general, to make our sampling appear to be random, as we theorise it should be, we use a computer to generate a random number, or an array of random numbers, depending on the application. Computers do this by making use of pseudo-random number generators (PRNGs). These generators start from a particular state, the (random) seed state, and start to apply different functions/algorithms over that seed to obtain the next results in the sequence. Many such functions exist. The one used in numpy for example is based on the very popular Mersenne Twister PRNG (it is also used in Excel, R, MATLAB, and so on).

Now you see why, when we set the seed, we obtain the same results. We are applying the same function to the same starting point so all the subsequent results can be derived by applying the same function. If we don't set the seed in Python, the initial seed value gets reseeded after every generation, i.e., it is replaced by another value from a pseudo-random sequence every time we run the code that is asked to make a selection.